browser=chrome
url=https://www.demoblaze.com/
username=test.kishore
password=ksr1009
screenshotPath=./screenshots/

name=Kishore
country=India
city=Hyderabad
card=1234567890123456
month=12
year=2025


